# Stage 1 - Build
FROM node:12-alpine as build
WORKDIR /usr/src/app

RUN apk update && \
    apk upgrade && \
    apk add --no-cache --virtual build-dependencies bash git openssh python make g++
# Install app dependencies

# Install event-pipeline-evm runtime dependencies
COPY event-pipeline-evm/package.json event-pipeline-evm/tsconfig.json ./event-pipeline-evm/
RUN cd event-pipeline-evm && yarn install --frozen-lockfile --production

COPY event-pipeline-evm event-pipeline-evm
#Start
WORKDIR /usr/src/app/event-pipeline-evm
RUN yarn build
CMD [ "yarn", "migrate_and_start" ]
