name: 0x-event-pipeline-sha
kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: publish-sha
    image: plugins/ecr
    settings:
      context: events-pipeline
      dockerfile: events-pipeline/Dockerfile
      repo:
        from_secret: ecr_repo_event-pipeline
      registry:
        from_secret: ecr_registry
      region: us-east-1
      tags:
        - ${DRONE_COMMIT_SHA}
trigger:
  event:
    exclude:
    - pull_request
node_selector:
  drone-builds: true
---
name: 0x-event-pipeline
kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: publish  
    image: plugins/ecr
    settings:
      context: events-pipeline
      dockerfile: events-pipeline/Dockerfile
      repo:
        from_secret: ecr_repo_event-pipeline
      registry:
        from_secret: ecr_registry
      region: us-east-1
      tags:
        - latest

trigger:
  branch:
  - master
  event:
    include:
      - push
node_selector:
  drone-builds: true
---
name: 0x-staking-api-sha
kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: publish-sha
    image: plugins/ecr
    settings:
      context: staking-api
      dockerfile: staking-api/Dockerfile
      repo:
        from_secret: ecr_repo_staking-api
      registry:
        from_secret: ecr_registry
      region: us-east-1
      tags:
        - ${DRONE_COMMIT_SHA}
trigger:
  event:
    exclude:
    - pull_request
node_selector:
  drone-builds: true
---
name: 0x-staking-api
kind: pipeline
type: kubernetes

platform:
  os: linux
  arch: amd64

steps:
  - name: publish  
    image: plugins/ecr
    settings:
      context: staking-api
      dockerfile: staking-api/Dockerfile
      repo:
        from_secret: ecr_repo_staking-api
      registry:
        from_secret: ecr_registry
      region: us-east-1
      tags:
        - latest

trigger:
  branch:
  - master
  event:
    include:
      - push
node_selector:
  drone-builds: true
