# Stage 1 - Build
FROM node:18-alpine as build
WORKDIR /usr/src/app

RUN apk add git python3 make g++

COPY package.json tsconfig.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY src src

#Start
RUN yarn build
CMD [ "yarn", "start" ]
