version: '3'
services:
    postgres:
        image: postgres:13.4
        environment:
          POSTGRES_USER: '${POSTGRES_USER}'
          POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
          POSTGRES_DB: '${POSTGRES_DB}'
          POSTGRES_PORT: ${POSTGRES_PORT}
        # persist the postgres data to disk so we don't lose it
        # on rebuilds.
        volumes:
            - ./mounts/postgres:/var/lib/postgresql/data
            - ./postgres-init.sql:/docker-entrypoint-initdb.d/postgres-init.sql
        ports:
            - '5432:5432'
        command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]

    event-pipeline-ethereum:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_ETHEREUM}'
            CHAIN_ID: '1'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events'
            # FEAT_EXCLUSIVE_TOKENS_FROM_TRANSACTIONS: "true"
            # TOKENS_FROM_TRANSACTIONS_START_BLOCK: 9193266
            KAFKA_BROKERS: '172.17.0.1:9092'
            EP_DEPLOYMENT_BLOCK: 10247094
            MAX_BLOCKS_TO_SEARCH: 1000
            MAX_BLOCKS_TO_PULL: 1000
            MAX_TX_TO_PULL: 1000
            MINUTES_BETWEEN_RUNS: 1
            FEAT_UNISWAP_V2_VIP_SWAP_EVENT: "true"
            UNISWAP_V2_VIP_SWAP_SOURCES: "UniswapV2,SushiSwap"
            UNISWAP_V2_VIP_SWAP_START_BLOCK: 10917104
            FEAT_UNISWAP_V3_VIP_SWAP_EVENT: "true"
            UNISWAP_V3_VIP_SWAP_START_BLOCK: 12553659
            FEAT_LIMIT_ORDERS: "true"
            V4_NATIVE_FILL_START_BLOCK: "11591021"
            FEAT_PLP_SWAP_EVENT: "true"
            PLP_VIP_START_BLOCK: 11377457
            FEAT_OTC_ORDERS: "true"
            OTC_ORDERS_FEATURE_START_BLOCK: 13143075
            FEAT_CANCEL_EVENTS: "true"
            FEAT_STAKING: "true"
            STAKING_DEPLOYMENT_BLOCK: 8952581
            FEAT_RFQ_EVENT: "true"
            FEAT_V3_NATIVE_FILL: "true"
            FEAT_ERC20_BRIDGE_TRANSFER_FLASHWALLET: "true"
            FLASHWALLET_ADDRESS: "0x22f9dcf4647084d6c31b2765f6910cd85c178c18"
            FLASHWALLET_DEPLOYMENT_BLOCK: 12231666
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 14258205
            FEAT_UNISWAP_V2_PAIR_CREATED_EVENT: "true"
            UNISWAP_V2_PAIR_CREATED_PROTOCOL_CONTRACT_ADDRESSES_AND_START_BLOCKS: "UniswapV2:0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f:10000835,SushiSwap:0xc0aee478e3658e2610c5f7a4a2e1777ce9e4f2ac:10794229"
            FEAT_UNISWAP_V2_SYNC_EVENT: "true"
            UNISWAP_V2_SYNC_START_BLOCK: 10000835

    event-pipeline-bsc:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_BSC}'
            CHAIN_ID: '56'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events_bsc'
            EP_DEPLOYMENT_BLOCK: 5375047
            MAX_BLOCKS_TO_SEARCH: 2000
            MAX_BLOCKS_TO_PULL: 5000
            MINUTES_BETWEEN_RUNS: 1
            FEAT_UNISWAP_V2_VIP_SWAP_EVENT: "true"
            UNISWAP_V2_VIP_SWAP_SOURCES: "PancakeSwap,BakerySwap,SushiSwap"
            FEAT_ONEINCH_SWAPPED_V3_EVENT: "true"
            ONEINCH_ROUTER_V3_DEPLOYMENT_BLOCK: 5300000
            FEAT_ONEINCH_SWAPPED_V4_EVENT: "true"
            ONEINCH_ROUTER_V4_DEPLOYMENT_BLOCK: 12386039
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 15860129
            FEAT_PARASWAP_SWAPPED2_V5_EVENT: "true"
            PARASWAP_V5_CONTRACT_ADDRESS: "0xdef171fe48cf0115b1d80b88dc8eab59176fee57"
            PARASWAP_V5_5_DEPLOYMENT_BLOCK: 15285647
            FEAT_OPEN_OCEAN_SWAPPED_V1_EVENT: "true"
            OPEN_OCEAN_V1_DEPLOYMENT_BLOCK: 10930110

    event-pipeline-polygon:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_POLYGON}'
            CHAIN_ID: '137'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events_polygon'
            ENABLE_PROMETHEUS_METRICS: "true"
            EP_DEPLOYMENT_BLOCK: 14391480
            MAX_BLOCKS_TO_SEARCH: 1000
            MAX_BLOCKS_TO_PULL: 1000
            MINUTES_BETWEEN_RUNS: 1
            FEAT_ONEINCH_SWAPPED_V3_EVENT: "true"
            ONEINCH_ROUTER_V3_DEPLOYMENT_BLOCK: 14500000
            FEAT_ONEINCH_SWAPPED_V4_EVENT: "true"
            ONEINCH_ROUTER_V4_DEPLOYMENT_BLOCK: 21008423
            FEAT_SLINGSHOT_TRADE_EVENT: "true"
            SLINGSHOT_DEPLOYMENT_BLOCK: 14500000
            FEAT_PARASWAP_SWAPPED_EVENT: "true"
            PARASWAP_DEPLOYMENT_BLOCK: 14500000
            PARASWAP_CONTRACT_ADDRESS: "0x90249ed4d69D70E709fFCd8beE2c5A566f65dADE"
            FEAT_LIMIT_ORDERS: "true"
            V4_NATIVE_FILL_START_BLOCK: "17587182"
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 25697854
            FEAT_OTC_ORDERS: "true"
            OTC_ORDERS_FEATURE_START_BLOCK: 26479109
            FEAT_PARASWAP_SWAPPED2_V5_EVENT: "true"
            PARASWAP_V5_CONTRACT_ADDRESS: "0xdef171fe48cf0115b1d80b88dc8eab59176fee57"
            PARASWAP_V5_5_DEPLOYMENT_BLOCK: 24981090
            FEAT_OPEN_OCEAN_SWAPPED_V1_EVENT: "true"
            OPEN_OCEAN_V1_DEPLOYMENT_BLOCK: 19409831
            FEAT_META_TRANSACTION_EXECUTED_EVENT: "true"
            META_TRANSACTION_EXECUTED_START_BLOCK: 39406300

    event-pipeline-avalanche:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_AVALANCHE}'
            CHAIN_ID: '43114'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events_avalanche'
            ENABLE_PROMETHEUS_METRICS: "true"
            EP_DEPLOYMENT_BLOCK: 3601700
            MAX_BLOCKS_TO_SEARCH: 5000
            MAX_BLOCKS_TO_PULL: 2000
            MINUTES_BETWEEN_RUNS: 1
            FEAT_ERC20_BRIDGE_TRANSFER_FLASHWALLET: "true"
            FLASHWALLET_ADDRESS: "0xdb6f1920a889355780af7570773609bd8cb1f498"
            FLASHWALLET_DEPLOYMENT_BLOCK: 11805869
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 11816835
            FEAT_PARASWAP_SWAPPED2_V5_EVENT: "true"
            PARASWAP_V5_CONTRACT_ADDRESS: "0xdef171fe48cf0115b1d80b88dc8eab59176fee57"
            PARASWAP_V5_5_DEPLOYMENT_BLOCK: 10965347
            FEAT_OPEN_OCEAN_SWAPPED_V1_EVENT: "true"
            OPEN_OCEAN_V1_DEPLOYMENT_BLOCK: 3794686

    event-pipeline-fantom:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_FANTOM}'
            CHAIN_ID: '250'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events_fantom'
            EP_ADDRESS: "0xDEF189DeAEF76E379df891899eb5A00a94cBC250"
            ENABLE_PROMETHEUS_METRICS: "true"
            EP_DEPLOYMENT_BLOCK: 18855765
            MAX_BLOCKS_TO_SEARCH: 2000
            MAX_BLOCKS_TO_PULL: 1000
            SECONDS_BETWEEN_RUNS: 60
            FEAT_ERC20_BRIDGE_TRANSFER_FLASHWALLET: "true"
            FLASHWALLET_ADDRESS: "0xb4d961671cadfed687e040b076eee29840c142e5"
            FLASHWALLET_DEPLOYMENT_BLOCK: 18855797
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 32817445
            FEAT_PARASWAP_SWAPPED2_V5_EVENT: "true"
            PARASWAP_V5_CONTRACT_ADDRESS: "0xdef171fe48cf0115b1d80b88dc8eab59176fee57"
            PARASWAP_V5_5_DEPLOYMENT_BLOCK: 31068544
            FEAT_OPEN_OCEAN_SWAPPED_V1_EVENT: "true"
            OPEN_OCEAN_V1_DEPLOYMENT_BLOCK: 16979047

    event-pipeline-celo:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_CELO}'
            CHAIN_ID: '42220'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events_celo'
            ENABLE_PROMETHEUS_METRICS: "true"
            EP_DEPLOYMENT_BLOCK: 9350111
            MAX_BLOCKS_TO_SEARCH: 5000
            MAX_BLOCKS_TO_PULL: 2000
            MINUTES_BETWEEN_RUNS: 1
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 11820000

    event-pipeline-optimism:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_OPTIMISM}'
            CHAIN_ID: '10'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events_optimism'
            EP_DEPLOYMENT_BLOCK: 1691335
            MAX_BLOCKS_TO_SEARCH: 1000
            MAX_BLOCKS_TO_PULL: 1000
            SECONDS_BETWEEN_RUNS: 30
            EP_ADDRESS: "0xDEF1ABE32c034e558Cdd535791643C58a13aCC10"
            # FEAT_ONEINCH_SWAPPED_EVENT: "true"
            # ONEINCH_ROUTER_V3_DEPLOYMENT_BLOCK: 14500000
            # FEAT_SLINGSHOT_TRADE_EVENT: "true"
            # SLINGSHOT_DEPLOYMENT_BLOCK: 14500000
            # FEAT_PARASWAP_SWAPPED_EVENT: "true"
            # PARASWAP_DEPLOYMENT_BLOCK: 14500000
            # PARASWAP_CONTRACT_ADDRESS: "0x90249ed4d69D70E709fFCd8beE2c5A566f65dADE"
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 4214981

    event-pipeline-arbitrum:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_ARBITRUM}'
            CHAIN_ID: '42161'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events_arbitrum'
            EP_DEPLOYMENT_BLOCK: 4050733
            MAX_BLOCKS_TO_SEARCH: 1000
            MAX_BLOCKS_TO_PULL: 1000
            SECONDS_BETWEEN_RUNS: 30
            EP_ADDRESS: "0xdef1c0ded9bec7f1a1670819833240f027b25eff"
            FEAT_NFT: "true"
            NFT_FEATURE_START_BLOCK: 4050733

    token-scraper-ethereum:
        depends_on:
            - postgres
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: always
        environment:
            ETHEREUM_RPC_URL: '${RPC_URL_ETHEREUM}'
            CHAIN_ID: '1'
            POSTGRES_URI: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}'
            SCHEMA: 'events'
            LOG_LEVEL: "info"
            FEAT_EXCLUSIVE_TOKENS_FROM_TRANSACTIONS: "true"
            TOKENS_FROM_TRANSACTIONS_START_BLOCK: 9193266
            EP_DEPLOYMENT_BLOCK: 10247094
            MAX_BLOCKS_TO_SEARCH: 1000
            MAX_BLOCKS_TO_PULL: 1000
            MAX_TX_TO_PULL: 1000
            SECONDS_BETWEEN_RUNS: 5